version: '3.8'

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: virtu_feedback_form_app
        container_name: virtu_feedback_form_app_container
        restart: unless-stopped
        volumes:
            - .:/var/www/app

    nginx:
        image: nginx:alpine
        container_name: virtu_feedback_form_nginx_container
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - .:/var/www
            - ./docker/virtu_feedback_form_nginx.conf:/etc/nginx/conf.d/default.conf

    db:
        image: postgres:14
        restart: unless-stopped
        container_name: virtu_feedback_form_db_container
        ports:
            - 54320:5432
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD:?Set password for main app database user}
            POSTGRES_USER: ${DB_USERNAME:?Set password for main app database user}
            POSTGRES_DB: ${DB_DATABASE:?Set password for main app database user}
